### ISSUE TITLE
Issues getting this going.

### ISSUE THREAD

**Issue by ucfncouch** [DonBrus/M5Stack-IDF-4.0#1]
Hey, having problems getting the submodules pulled down and can't get things working. I do see that this is a little old at this point. Is there another way to get M5Stack boards working in the ESP-IDF now? I have been searching around but haven't found anything besides their old repo and this one which I have not gotten to work.

I am really hoping there is an easier way to get these boards up and running. Arduino ide will simply not work for what I am trying to do.

**Comment by DonBrus** [comment]
Hi @ucfncouch, yeah this repo isn't being actively maintained, I apologize for not making this clear in the readme. It was created as a one-off project to help some people out in the M5Stack forums.
As for official support I know there's https://github.com/m5stack/M5Unified which aims to make a framework independent library for all of their boards, but I've personally haven't used it yet; it seems someone has worked out a way to use it on IDF 4.x.x, not sure about version 5.

Lately the only boards I use from M5Stack are Atoms, which I manage mainly just using esp-idf. Last time I wanted a gui out of a Core I had some luck using lvgl.

**Comment by ucfncouch** [comment]
Hey, no worries at all I appreciate the response. Got a couple of the M5Stack ESP32 boards and have been trying to get them working in esp-idf, no luck so far but I will take a look at what you linked here and try some other ideas as well. Good luck on your projects!

**Comment by DonBrus** [comment]
@ucfncouch thanks, good luck to you too :) if you need help with that, just reopen the issue
